######################################################################
# Automatically generated by qmake (2.01a) Tue Nov 11 15:35:59 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug release
INCLUDEPATH += .

# Input
HEADERS += facemanager.h funeyes.h global.h ui_faceinfodialog.h
FORMS += facemanager.ui
SOURCES += facemanager.cpp funeyes.cpp global.cpp main.cpp
RESOURCES += funeyes.qrc
RC_FILE = funeyes.rc